### ISSUE TITLE
ERRO: Ativo não encontrado, escolha outro

### ISSUE THREAD

**Issue by lucasdobr15** [MatheusGatti/Copiador-De-Entradas#12]
Após colocar meu e-mail e senha, loga 
![Screenshot_1](https://user-images.githubusercontent.com/12130053/111011145-48c2b980-8377-11eb-8e02-9c07a534d3b4.jpg)
normalmente, porém na etapa de escolher o tipo de ativo, colocando o padrão EURUSD, retorno o erro como mostrado no imagem abaixo, testei outros ativos porém me retorna o mesmo erro, já testei tanto no modo gráfico quanto no cli, porém o erro persiste, como proceder?

LOG DE ERROS:

12-03-2021 21:57:03 ERROR: O ativo EURUSD nao foi encontrado
12-03-2021 21:57:46 ERROR: O ativo USDJPY nao foi encontrado
12-03-2021 21:58:01 ERROR: O ativo GBPUSD nao foi encontrado
12-03-2021 21:58:12 ERROR: O ativo AUDUSD nao foi encontrado
12-03-2021 21:58:26 ERROR: O ativo EURGBP nao foi encontrado
12-03-2021 21:58:36 ERROR: O ativo USDCAD nao foi encontrado

**Comment by MatheusGatti** [comment]
Olá Lucas, sinto muito mas o projeto está desatualizado e não pretendo dar continuidade a ele, caso queira é só realizar um fork e fazer suas próprias mudanças e implementações no projeto.
