### ISSUE TITLE
Volta com o projeto!

### ISSUE THREAD

**Issue by KairosGG** [MatheusGatti/Copiador-De-Entradas#14]
Queria muito ver esse projeto em ação, estive baixando e dando uma olhada e achei incrível, porém infelizmente o robô não faz entradas mais! Tem algum meio de contato que possa falar com você?
Abraços, parabéns.

**Comment by MatheusGatti** [comment]
Fala comigo irmão, tenho sim, meu Instagram, pode encontrar no meu perfil aqui do GitHub. Mas infelizmente não há chances de voltar com o projeto e obrigado por gostar.
