### ISSUE TITLE
Pegar entradas conta demo

### ISSUE THREAD

**Issue by Aridesk** [MatheusGatti/Copiador-De-Entradas#4]
O que eu poderia fazer aqui para pegar entradas apenas de traders que estão operando com dinheiro real ao em vez de pegar treinamento / real?

**Comment by ElLuigi** [comment]
Tenho a mesma pergunta, pode ser diferente de onde você copia, de uma conta real ou demo?

**Comment by MatheusGatti** [comment]
Creio que a biblioteca utilizada não disponibiliza "detectar" esta diferença.
