### ISSUE TITLE
Analisar mais de um ativo ao mesmo tempo

### ISSUE THREAD

**Issue by dexter00x** [MatheusGatti/Copiador-De-Entradas#5]
Bom dia. Saberia me informar se seria possível alterar o sistema para analisar mais de um ativo ao mesmo do tempo do trader?

**Comment by IgGarcia1** [comment]
@dexter00x, bom dia. Não cheguei a me aprofundar no código, mas acredito que seja possível manter o mesmo código de análise dos ativos e ainda sim conseguir ver mais de um ativo ao mesmo tempo. Você só precisaria criar uma função intermediária utilizando threadings. Para ter mais clareza de como fazer, você pode ler isto: [Entendendo threadings](https://pt.stackoverflow.com/questions/143552/entendendo-o-conceito-de-threads-na-pr%C3%A1tica-em-python) e a[ documentação oficial das threadings em Python](https://docs.python.org/3/library/threading.html)
