### ISSUE TITLE
Não está realizando as entradas

### ISSUE THREAD

**Issue by williampasini07** [MatheusGatti/Copiador-De-Entradas#9]
Primeiramente quero te parabenizar pelo trabalho que realizou!
E segundo estou utilizando o arquivo mas não está copiando para a minha conta, exemplo, ele mostra que os traders fizeram as entradas mas ele não realiza as entradas na minha conta.
Tem alguma configuração a ser feita para que funcione?
Fico no aguardo.
Obrigado.

**Comment by MatheusGatti** [comment]
Você deve configurar qual até qual posição mundial deseja aceitar as entradas, caso tenha escolhido e mesmo assim não copia as entradas, a biblioteca pode estar desatualizada.
